### ISSUE TITLE
Gadget compilation for complete utilization of available memory

### ISSUE THREAD

**Issue by SaeeDhawalikar** [a-paranjape/sahyadri-sandbox#15]
The new version of gadget available on the official page supports complete utilization of the available memory.
1. In config.sh, line 203 must be commented out:
#OLDSTYLE_SHARED_MEMORY_ALLOCATION            # disables new memory allocation mechanism via memfd_create()

2. Add the following line in the Config.sh file:
ALLOC_TOLERANCE=0.01

3. For 2048^3 particles, in config.sh, line 107,: IDS_64BIT should be un-commented.

**Comment by a-paranjape** [comment]
all done after pulling latest Gadget-4 commit. all binaries recompiled. test 128^3 job submitted, will report results soon.

**Comment by a-paranjape** [comment]
job ran successfully on 2 nodes with maxmemsize = 11000, thus using all available memory.

**Comment by shadaba** [comment]
I am having my runs to fails due to memory issues so I am curious about this setting.
This 11GB run was for what particle number? for me so far 1024^3 rune 768 GB memory is not enough!

**Comment by a-paranjape** [comment]
11GB was for 256^3 particles only! sorry for the confusion.

**Comment by a-paranjape** [comment]
the 11GB was only an example. @SaeeDhawalikar can maybe mention a formula for MaxMemSize that can be used with arbit particle number?

**Comment by SaeeDhawalikar** [comment]
Total memory usage is approx M= 0.45*Npart/1000 (MB), where e.g. Npart=256^3. 
MaxMemSize should be at least M/Ncpu. But, this should actually be set to a number close to the available memory per cpu, as gadget makes efficient use of any extra memory available. Pegasus nodes have 384 GB RAM (12 GB per cpu), so MaxMemSize was se to 11 GB.

**Comment by shadaba** [comment]
Thanks Aseem, I think Saee already told me this formula
0.45*Npart^3 in KB --> this means for 1024 should require 460 GB.
My jobs when very quickly uses about 7GB with 2GB free and rest in buff/cache about 750GB or so.
My guess is the buff cached is what Gadget is using. But at some point of time around snapshot 24 this becomes out of memory. 
This is already more memory than I was expecting for a 1024 run so trying to track various things to see why this is happening. I have just submitted a job with the setting recommended in this thread to see if this help.

**Comment by shadaba** [comment]
@SaeeDhawalikar and @a-paranjape my 1024 simulation still fails with memory issue.
Is it possible for you too look at any 1024 run and state the maximum memory used across the time?
My node has 768 GB memory on which I has successfully ran 512^3 sim but 1024^3 fails after a while due to out of memory. The maximum it has worked till 24 snapshot in some attempts. I must be not using the best possible setting.
