### ISSUE TITLE
Compilation using Intel

### ISSUE THREAD

**Issue by SaeeDhawalikar** [a-paranjape/sahyadri-sandbox#17]
Using Intel compiler provides ~50% speedup in walltime.

* module add  null gcc/11.2.0 cmake-3.15.4  Intel_OneAPI-v2023 hdf5-1.14.2_P_intel_oneAPI fftw-3.3.10 gsl-2.8
*  Create Makefile.comp.intelpegasus in gadget4/buildsystem, and paste the contents of the attached file in it.
* In Makefile.systype, add: SYSTYPE="Intel-Pegasus", comment out SYSTYPE="Intel-Pegasus"
* In Makefile, add the lines:
ifeq ($(SYSTYPE),"Intel-Pegasus")
include buildsystem/Makefile.comp.intelpegasus
include buildsystem/Makefile.path.pegasus
endif

* Compile the gadget executables.
* in run_gadget.sh, change " mpirun -np $NCPU_TOT" to " mpirun -bootstrap ssh -np $NCPU_TOT"

Note that the hdf5 module used has to be intel compatible.

[Makefile.comp.intelpegasus.txt](https://github.com/user-attachments/files/17147506/Makefile.comp.intelpegasus.txt)

**Comment by a-paranjape** [comment]
are the outputs identical to those with the earlier compilers?

**Comment by SaeeDhawalikar** [comment]
The simulations aren't complete yet. I'll make changes in the issue once
all the tests are done within a couple of days.

**Comment by SaeeDhawalikar** [comment]
The speedup is not because of using intel compiler, but different modules.
On pegasus, gcc and intel compilers give comparable cpu time.  So there is no need to shift to intel.
